#Prgramming language used
language: python
#Language version
python:
  - "3.6"
#Installation
services:
  - postgresql

before_script:
  - psql -c 'create database diary_db_test;' -U postgres
#  - psql -c 'alter role postgres password 'postgres';' -U postgres

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

install:
- pip install -r requirements.txt
# command to run tests
script:
  - pytest
after_success:
  - coverage run -m pytest
